### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by georgeoshardo** [sylvainprigent/sdeconv#2]
Thanks for producing this package. I've used it in a manuscript I'm writing and I'm wondering if there is any particular way you want this package cited? Is there a publication for which this package was produced maybe? Additionally I saw no CITATION.cff file in the repo. 
Thanks again!

**Comment by sylvainprigent** [comment]
Hello,

Thanks for using and citing the package. 
We have not yet a dedicated publication for the package. Nevertheless, you can site our deconvolution paper that was made using this package: https://www.nature.com/articles/s41598-022-26178-y
