### ISSUE TITLE
SPSFgaussian always symmetrical

### ISSUE THREAD

**Issue by nal10** [sylvainprigent/sdeconv#3]
Hi,

It looks like the code for creating 3D Gaussian PSFs needs () added around the sigma

https://github.com/sylvainprigent/sdeconv/blob/main/sdeconv/psfs/gaussian.py#L53

as currently written the sigma in each dimension ends up at 0.5

**Comment by sylvainprigent** [comment]
Hi,

Thanks for pointing this out.
I updated the code and made a new release v1.0.3 with the fix.
